export const questionsData = [
  { id: 0, letter: 'أ', question: 'ما هو الحيوان الذي يلقب بملك الغابة؟', answer: 'أسد' },
  { id: 1, letter: 'ب', question: 'ما هي عاصمة فرنسا؟', answer: 'باريس' },
  { id: 2, letter: 'ت', question: 'ما هي الفاكهة التي سقطت على رأس نيوتن؟', answer: 'تفاح' },
  { id: 3, letter: 'ث', question: 'حيوان يضرب به المثل في المكر والخداع؟', answer: 'ثعلب' },
  { id: 4, letter: 'ج', question: 'ما هي أكبر دولة عربية من حيث المساحة؟', answer: 'جزائر' },
  { id: 5, letter: 'ح', question: 'معدن قوي يرمز له كيميائياً بالرمز Fe؟', answer: 'حديد' },
  { id: 6, letter: 'خ', question: 'ما هو الحيوان الثديي الوحيد القادر على الطيران؟', answer: 'خفاش' },
  { id: 7, letter: 'د', question: 'ما هي أقدم عاصمة مأهولة في العالم؟', answer: 'دمشق' },
  { id: 8, letter: 'ذ', question: 'معدن نفيس لونه أصفر؟', answer: 'ذهب' },
  { id: 9, letter: 'ر', question: 'ما هو العضو المسؤول عن التنفس في جسم الإنسان؟', answer: 'رئة' },
  { id: 10, letter: 'ز', question: 'ما هو أطول حيوان بري في العالم؟', answer: 'زرافة' },
  { id: 11, letter: 'س', question: 'وسيلة نقل اخترعها كارل بنز؟', answer: 'سيارة' },
  { id: 12, letter: 'ش', question: 'ما هو النجم الذي يمد الأرض بالحرارة والضوء؟', answer: 'شمس' },
  { id: 13, letter: 'ص', question: 'ما هي الدولة العربية التي تقع في القرن الأفريقي؟', answer: 'صومال' },
  { id: 14, letter: 'ض', question: 'حيوان برمائي يشتهر بالنقيق؟', answer: 'ضفدع' },
  { id: 15, letter: 'ط', question: 'ما هي عاصمة اليابان؟', answer: 'طوكيو' },
  { id: 16, letter: 'ظ', question: 'حيوان صحراوي رشيق يشبه الغزال؟', answer: 'ظبي' },
  { id: 17, letter: 'ع', question: 'دولة عربية يمر بها نهرا دجلة والفرات؟', answer: 'عراق' },
  { id: 18, letter: 'غ', question: 'مساحة كبيرة من الأرض تغطيها الأشجار الكثيفة؟', answer: 'غابة' },
  { id: 19, letter: 'ف', question: 'ما هو أضخم حيوان بري على وجه الأرض؟', answer: 'فيل' },
  { id: 20, letter: 'ق', question: 'ما هي عاصمة جمهورية مصر العربية؟', answer: 'قاهرة' },
  { id: 21, letter: 'ك', question: 'تجويف طبيعي سطحي أو جوفي في صخرة أو جبل بعضها داخلي و بعضها سطحي', answer: 'الكهف' },
  { id: 22, letter: 'ل', question: 'فاكهة حمضية لونها أصفر غنية بفيتامين سي؟', answer: 'ليمون' },
  { id: 23, letter: 'م', question: 'ما هو الكوكب الملقب بالكوكب الأحمر؟', answer: 'مريخ' },
  { id: 24, letter: 'ن', question: 'ما هو أطول نهر في العالم؟', answer: 'نيل' }
];
